[project]
name = "projet"
version = "0.1.0"
description = "This is a test"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gymnasium>=1.2.2",
    "numpy>=2.3.5",
    "pandas>=2.3.3",
    "stable-baselines3>=2.7.1",
]
